using System;
using System.Collections.Generic;

namespace Republish.Models
{
    public class Cases
    {
        public int Id { get; set; }
        public string CaseId { get; set; }
        public string CaseName { get; set; }
        public int FirmId { get; set; }
        public int? OwnerId { get; set; }
        public int? FirmAddressId { get; set; }
        public int? EmpId { get; set; }
        public string EmpAccess { get; set; }
        public string Paralegal { get; set; }
        public string CaseStatus { get; set; }
        public string InsCaseNum { get; set; }
        public string ClassFicn { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastWorked { get; set; }
        public int? AlienId { get; set; }
        public string NotifyTo { get; set; }
        public string PageLinkNum { get; set; }
        public string EtaCaseNum { get; set; }
        public DateTime? LcaFrom { get; set; }
        public DateTime? LcaTo { get; set; }
        public DateTime? H1priorityDate { get; set; }
        public DateTime? H1rectCloseDate { get; set; }
        public DateTime? H1finalDocsDate { get; set; }
        public DateTime? H1transmitDate { get; set; }
        public string LcAssignedTo { get; set; }
        public DateTime? LcFilingDate { get; set; }
        public DateTime? LcRecttCloseDate { get; set; }
        public DateTime? LcDocsSentDate { get; set; }
        public DateTime? LcDolSentDate { get; set; }
        public DateTime? LcApproveDate { get; set; }
        public string LcApproveNum { get; set; }
        public DateTime? LcCallupDate { get; set; }
        public string I140assignedTo { get; set; }
        public DateTime? I140docsOut { get; set; }
        public DateTime? I140docsBack { get; set; }
        public string I140filedAt { get; set; }
        public DateTime? I140filingDate { get; set; }
        public string I140filingNum { get; set; }
        public DateTime? I140approveDate { get; set; }
        public string I140approveNum { get; set; }
        public DateTime? I140callUpDate { get; set; }
        public string I130assignedTo { get; set; }
        public string I130categ { get; set; }
        public DateTime? I130docsOut { get; set; }
        public DateTime? I130docsBack { get; set; }
        public string I130filedAt { get; set; }
        public DateTime? I130filingDate { get; set; }
        public string I130filingNum { get; set; }
        public DateTime? I130approveDate { get; set; }
        public string I130approveNum { get; set; }
        public DateTime? I130callUpDate { get; set; }
        public string AosAssignedTo { get; set; }
        public string AosCateg { get; set; }
        public DateTime? AosDocsOut { get; set; }
        public DateTime? AosDocsBack { get; set; }
        public string AosFiledAt { get; set; }
        public DateTime? AosFilingDate { get; set; }
        public string AosFilingNum { get; set; }
        public DateTime? AosFingerPrintDate { get; set; }
        public DateTime? AosApproveDate { get; set; }
        public string AosApproveNum { get; set; }
        public DateTime? AosCallUpdate { get; set; }
        public int? PrefType { get; set; }
        public string PrefCateg { get; set; }
        public DateTime? PrefPd { get; set; }
        public int? Process { get; set; }
        public int? Processtype { get; set; }
        public DateTime? Submittedate { get; set; }
        public DateTime? Interviewdate { get; set; }
        public DateTime? Fingerprintdate { get; set; }
        public int? Updatedby { get; set; }
        public DateTime? ExpDate { get; set; }
        public bool? MainCase { get; set; }
        public string CaseRelationship { get; set; }
        public DateTime? Processdateupdate { get; set; }
        public DateTime? Approvaldate { get; set; }
        public int? Archived { get; set; }
        public int? EmployerAddressId { get; set; }
        public int? CaseCountry { get; set; }
        public int? Signatoryid { get; set; }
        public bool? Empforms { get; set; }
        public string Empformstxt { get; set; }
        public bool? UscisXfer { get; set; }
        public int? Defaultrecpt { get; set; }
        public DateTime? Closedon { get; set; }
        public string CostCenter { get; set; }
        public string Reasonclosed { get; set; }
        public bool Eb5 { get; set; }
        public int? RegCenter { get; set; }
        public int? RegCm { get; set; }
        public int? RegEnt { get; set; }
        public int? Agent { get; set; }
        public int? AgentCm { get; set; }
        public int? BillingFile { get; set; }
    }
}
